rootOAuthIds:
  - default
oauth:
  webClientId: default
  webClientSecret: default
  nativeClientId: default
  nativeClientSecret: default
  domain: default
  apiToken: default
imgur:
  url: https://imgur-apiv3.p.mashape.com
  clientId: default
  clientSecret:
  mashapeKey: default

facialRecognition:
  frontFaceClassifierPath: src/main/resources/haarcascade_frontalface_default.xml

databases:
  - 127.0.0.1:27017

server:
  gzip:
    enabled: false
  applicationConnectors:
    - type: https
      port: 443
      keyStorePath: /root/tls_copy/keystore.jks
      keyStorePassword: default
      validateCerts: false
      trustStorePath: /root/tls_copy/keystore.jks
      certAlias: server

logging:
  level: INFO
  loggers:
    "io.dropwizard": ALL

  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      maxFileSize: 100MB
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC